### ISSUE TITLE
Fix initial Homepage page view

### ISSUE THREAD

**Issue by SloppyFlipFlop** [posterboard-io/posterboard#28]
<img width="1280" alt="Screenshot 2024-02-12 at 6 35 16 PM" src="https://github.com/posterboard-io/posterboard/assets/69279785/c26a48ac-2ddd-4b3c-bdbf-879226a7f098">

content should be in the center of the page

**Comment by tkruer** [comment]
Thanks for letting me know! This was just fixed so closing issue.
